# Site settings
name: Soham Petkar
url: "https://tenseisoham.github.io"
avatar: images/soham_main_pic.JPG

permalink: /

# Jekyll 3 - Kramdown + Rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CNAME
